apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: abc-123-gitops
  description: This is GitOps manifest for abc-123   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: abc-123
    janus-idp.io/tekton: abc-123 
    backstage.io/kubernetes-id: abc-123 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:abc-123
