apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: abc-123
  janus-idp.io/tekton: abc-123
  backstage.io/kubernetes-id: abc-123
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: abc-123
resources:
- deployment.yaml
- route.yaml
- service.yaml
