apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: abc-123
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: abc-123 
  name: abc-123
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: abc-123
    weight: 100 
