apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: abc-123
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: abc-123 
  name: abc-123
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: abc-123 
